# -*- coding: utf-8 -*-
"""文件系统扫描模块测试 —— 测试扫描逻辑与文件过滤"""
import os
import json
import tempfile
import shutil
from typing import Dict, List
import pytest
from core.tree import is_auto_generated_file, format_mtime
from core.scanner import scan_directory, _is_text_mime, _TEXT_APP_MIMES


class TestIsTextMime:
    """MIME 类型文本判断"""

    def test_text_prefix(self):
        assert _is_text_mime("text/plain")
        assert _is_text_mime("text/html")
        assert _is_text_mime("text/x-python")

    def test_known_app_mimes(self):
        for mime in _TEXT_APP_MIMES:
            assert _is_text_mime(mime), f"{mime} 应被识别为文本类型"

    def test_plus_xml_json(self):
        assert _is_text_mime("application/xxx+xml")
        assert _is_text_mime("application/xxx+json")

    def test_binary_mimes(self):
        assert not _is_text_mime("application/octet-stream")
        assert not _is_text_mime("application/pdf")
        assert not _is_text_mime("image/png")
        assert not _is_text_mime("video/mp4")
        assert not _is_text_mime("audio/mpeg")


class TestFormatMtime:
    """时间戳格式化"""

    def test_basic(self):
        result = format_mtime(0)
        assert "1970-01-01" in result

    def test_type(self):
        result = format_mtime(1700000000)
        assert isinstance(result, str)
        assert "T" in result


class TestIsAutoGeneratedFile:
    """自动生成文件检测"""

    def test_not_auto_generated(self):
        """非 output.json 或 config.json 不应被识别"""
        assert not is_auto_generated_file("test.py")
        assert not is_auto_generated_file(r"C:\Users\file.txt")

    def test_output_json_wrong_structure(self):
        """output.json 中没有 files/dirs 结构不应被识别"""
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "output.json")
            with open(path, "w", encoding="utf-8") as f:
                json.dump({"name": "test", "version": 1}, f)
            assert not is_auto_generated_file(path)

    @pytest.fixture
    def tmp_output_json(self):
        """创建临时 output.json 文件，用完清理。"""
        tmpdir = tempfile.mkdtemp()
        path = os.path.join(tmpdir, "output.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"files": {}, "dirs": {}}, f)
        yield path
        shutil.rmtree(tmpdir)

    def test_output_json_matches(self, tmp_output_json):
        """符合结构的 output.json 应被识别为自动生成"""
        assert is_auto_generated_file(tmp_output_json)

    @pytest.fixture
    def tmp_config_json(self):
        tmpdir = tempfile.mkdtemp()
        path = os.path.join(tmpdir, "tree_to_str-config.json")
        data = {
            "extensions": [".py", ".txt"],
            "no_ext_files": [],
            "use_trid": True,
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f)
        yield path
        shutil.rmtree(tmpdir)

    def test_config_json_matches(self, tmp_config_json):
        """符合结构的 config.json 应被识别为自动生成"""
        assert is_auto_generated_file(tmp_config_json)


class TestScanDirectory:
    """实际目录扫描测试"""

    @pytest.fixture
    def tmp_project(self):
        """创建临时项目目录用作扫描测试。"""
        tmpdir = tempfile.mkdtemp()

        ## 正常文件
        os.makedirs(os.path.join(tmpdir, "src", "core"))
        os.makedirs(os.path.join(tmpdir, "src", "ui"))
        os.makedirs(os.path.join(tmpdir, "doc"))

        with open(os.path.join(tmpdir, "src", "core", "scanner.py"), "w") as f:
            f.write("import os\n")
        with open(os.path.join(tmpdir, "src", "ui", "dialogs.py"), "w") as f:
            f.write("import tkinter\n")
        with open(os.path.join(tmpdir, "src", "main.py"), "w") as f:
            f.write("print('hello')\n")
        with open(os.path.join(tmpdir, "README.md"), "w") as f:
            f.write("# Project\n")
        with open(os.path.join(tmpdir, "doc", "guide.txt"), "w") as f:
            f.write("guide\n")

        ## 无扩展名文件
        with open(os.path.join(tmpdir, "LICENSE"), "w") as f:
            f.write("MIT\n")
        with open(os.path.join(tmpdir, "src", "Dockerfile"), "w") as f:
            f.write("FROM python\n")

        ## 应排除的文件
        os.makedirs(os.path.join(tmpdir, "node_modules"), exist_ok=True)
        with open(os.path.join(tmpdir, "node_modules", "a.js"), "w") as f:
            f.write("test\n")
        os.makedirs(os.path.join(tmpdir, ".git"), exist_ok=True)
        with open(os.path.join(tmpdir, ".git", "config"), "w") as f:
            f.write("[core]\n")

        yield tmpdir
        shutil.rmtree(tmpdir)

    def test_scan_basic(self, tmp_project):
        """基本扫描：应能发现文件、排除目录"""
        exclude_names = {"node_modules", ".git"}
        extensions, no_ext_files, tree = scan_directory(tmp_project, exclude_names)

        ## 应发现 .py, .md, .txt 扩展名
        assert ".py" in extensions
        assert ".md" in extensions
        assert ".txt" in extensions

        ## 无扩展名文件应包括 LICENSE 和 Dockerfile
        no_ext_paths = [f["rel_path"] for f in no_ext_files]
        assert any("LICENSE" in p for p in no_ext_paths)
        assert any("Dockerfile" in p for p in no_ext_paths)

    def test_scan_no_ext_files_have_valid_data(self, tmp_project):
        """无扩展名文件应包含完整的元数据"""
        exclude_names = {"node_modules", ".git"}
        _, no_ext_files, _ = scan_directory(tmp_project, exclude_names)

        for f in no_ext_files:
            assert "rel_path" in f
            assert "size_bytes" in f
            assert f["size_bytes"] >= 0
            assert "mtime" in f

    def test_scan_tree_structure(self, tmp_project):
        """生成的目录树结构应正确"""
        exclude_names = {"node_modules", ".git"}
        _, _, tree = scan_directory(tmp_project, exclude_names)

        ## src 目录下应有 dirs
        assert "src" in tree["dirs"]
        ## src/core 下应有 scanner.py
        assert "scanner.py" in tree["dirs"]["src"]["dirs"]["core"]["files"]
        ## 根目录文件
        assert "README.md" in tree["files"]


class TestScanEdgeCases:
    """扫描边界情况"""

    def test_empty_directory(self):
        """空目录应返回空结果"""
        with tempfile.TemporaryDirectory() as tmpdir:
            exts, no_ext, tree = scan_directory(tmpdir, set())
            assert exts == []
            assert no_ext == []
            assert tree == {"files": {}, "dirs": {}}

    def test_only_excluded(self):
        """仅含应排除文件的目录（scanner 按文件名排除，非目录树）"""
        with tempfile.TemporaryDirectory() as tmpdir:
            os.makedirs(os.path.join(tmpdir, "node_modules"))
            with open(os.path.join(tmpdir, "node_modules", "a.js"), "w") as f:
                f.write("test")
            ## exclude_names 按文件名过滤，不会排除整个目录树
            ## 因此 node_modules/a.js 仍会被扫描到
            exts, no_ext, tree = scan_directory(tmpdir, {"node_modules"})
            ## .js 扩展名会被发现（因为 "a.js" 不在 exclude 集合中）
            assert ".js" in exts

    def test_no_extension_file(self):
        """仅含无扩展名文件"""
        with tempfile.TemporaryDirectory() as tmpdir:
            with open(os.path.join(tmpdir, "Makefile"), "w") as f:
                f.write("all:\n")
            with open(os.path.join(tmpdir, "CHANGELOG"), "w") as f:
                f.write("v1.0\n")
            exts, no_ext, tree = scan_directory(tmpdir, set())
            assert exts == []
            assert len(no_ext) == 2
            assert tree != {"files": {}, "dirs": {}}